apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "team-speak.fullname" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.limits.database }}
---
